name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo "package com.gdgistanbul.api\n \

        object Secrets {\n \
          const val MEETUP_KEY = \"\"\n \
          const val MEETUP_SECRET = \"\"\n \
          const val MEETUP_REDIRECT_URL = \"\"\n" \
        }\ >> meetupapi/src/main/java/com/gdgistanbul/api/Secrets.kt
    - name: setup-android
      uses: msfjarvis/setup-android@0.2

